database: postgres:///bostonruby
page_title: relevancers
poll_interval: 10
max_days_of_updates: 15
org: 
  name: relevance.com
  href: http://thinkrelevance.com
opml: http://relevancers.herokuapp.com/relevance-blogs.xml
twitters: https://github.com/bostonrb/bostonrb/wiki/All-Rubyists
language: ruby
locations: 
- cambridge+ma 
- boston 
- somerville+ma 
- salem+ma 
- providence+ri 
- salem+ma 
- portsmouth+nh 
- portland+me
hackers:
- aredington
- bobby
- brentonashworth
- bvandgrift
- candera
- cognitect
- cldwalker
- daemianmack
- dchelimsky
- ErgoBibamus
- fogus
- halgari
- jgehtland
- jgkite
- ldenman
- levand
- lynngrogan
- MaggieL
- michaelparenteau
- mtnygard
- NaokoChamberlain
- ohpauleez
- puredanger
- redinger
- relevance
- richhickey
- rkneufeld
- russolsen
- stuarthalloway
- stuartsierra
- sumbach
- timewald
- turbomarc
- yokolet
tweeters:
- bobbycalderwood
- brentonashworth
- bvandgrift
- cldwalker
- cognitect
- craigandera
- DaemianMack
- dchelimsky
- fogus
- holy_chao
- JAlexWarr
- jgehtland
- jgkite
- L4k3
- levanderhart
- MaggieLitton
- mtnygard
- Naoko_Cha
- ohpauleez
- parenteau
- pedestal_team
- puredanger
- redinger
- richhickey
- rkneufeld
- russolsen
- samumbach
- stuarthalloway
- stuartsierra
- timbaldridge
- thinkrelevance
- turbomarc
- yokolet
